#! /usr/bin/env python
# encoding: utf-8

import glob, os

sources_with_main = ["window_with_button.cpp"]

def build(bld):
    """..."""
    print(
        "building at source path",
        bld.path.srcpath())
    cpp_files ={
        file.split("/")[-1]
        for file in glob.glob(
                bld.path.abspath() + "/*.cpp")}
    print(
        "Source files: ",
        cpp_files)
    includes =\
        ["../../" + x for x in bld.env.INCLUDES_REL] + bld.env.INCLUDES_ABS
    bld.objects(
        source=cpp_files.difference(sources_with_main),
        target="tutorial",
        includes=includes,
        cxxflags=bld.env.CXXFLAGS)
    bld.env.append_unique(
        "targets",
        os.path.join(
            bld.path.srcpath(),
            "window-with-button"))
    bld.program(
        source="window_with_button.cpp",
        use=["FS"],
        target="window-with-button",
        stlib=bld.env.STLIB,
        cxxflags=bld.env.CXXFLAGS,
        includes=includes,
        lib=bld.env.LDFLAGS_N)


